import os

# Set up flags for debug and for production.
CCFLAGS = '-O2' if ARGUMENTS.get('production', False) else '-g'
env = Environment(CCFLAGS=CCFLAGS)

# Get CC from environment
CC = os.getenv('CC', env['CC'])
env['CC'] = CC

# ...and configure -std flag appropriately.
CSTD = '-std=c1x' if CC == 'gcc' else '-std=c11'
env.Append(CCFLAGS=[CSTD])

# Libraries.
stb_image = ['stb_image.c']
stb_image_resize = ['stb_image_resize.c']
rgbtree = ['rgbtree.c']
libraries = rgbtree + stb_image + stb_image_resize

# The actual program.
program = env.Program(target='imgcat', source=['imgcat.c'] + libraries)
Return('program')
