# Set up flags for debug and for production.
CCFLAGS = '-O2' if ARGUMENTS.get('production', False) else '-g'
env = Environment(CCFLAGS=CCFLAGS)
env.Append(CCFLAGS=['-std=c11'])

# Libraries.
stb_image = ['stb_image.c']
stb_image_resize = ['stb_image_resize.c']
rgbtree = ['rgbtree.c']
libraries = rgbtree + stb_image + stb_image_resize

# The actual program.
program = env.Program(target='imgcat', source=['imgcat.c'] + libraries)
Return('program')
